echo \
"
STACKUP_NOTIFICATION_PORT=${STACKUP_NOTIFICATION_PORT:-3003}
STACKUP_NOTIFICATION_NETWORK_ENV=${STACKUP_NOTIFICATION_NETWORK_ENV:-testnet}
STACKUP_NOTIFICATION_MONGODB_URL=${STACKUP_NOTIFICATION_MONGODB_URL:-mongodb://127.0.0.1:27020/app}
STACKUP_NOTIFICATION_SENTRY_DSN=${STACKUP_NOTIFICATION_SENTRY_DSN}
STACKUP_NOTIFICATION_FIREBASE_SERVICE_ACCOUNT=${STACKUP_NOTIFICATION_FIREBASE_SERVICE_ACCOUNT}
STACKUP_NOTIFICATION_ALCHEMY_AUTH_TOKEN=${STACKUP_NOTIFICATION_ALCHEMY_AUTH_TOKEN}
STACKUP_NOTIFICATION_WEBHOOK_URL=${STACKUP_NOTIFICATION_WEBHOOK_URL}
STACKUP_NOTIFICATION_PREFERRED_IP_HEADER=${STACKUP_NOTIFICATION_PREFERRED_IP_HEADER}" \
> .env

echo "Env files successfully generated."
